// app/tenants/[subdomain]/layout.tsx
import {headers} from "next/headers";
import {redirect} from "next/navigation";
import {Sidebar} from "@/components/platform/dashboard/Sidebar";
import {DashboardHeader} from "@/components/platform/dashboard/Header";
import {LayoutDashboard, Search, Settings, Wallet} from "lucide-react";
import {cn} from "@/lib/utils";
import {Geist, Geist_Mono, Inter} from "next/font/google";
import type {Metadata} from "next";
import "../../globals.css";
import QueryProvider from "@/components/providers/query-provider";

const inter = Inter({subsets:['latin'],variable:'--font-sans'});

const geistSans = Geist({
    variable: "--font-geist-sans",
    subsets: ["latin"],
});

const geistMono = Geist_Mono({
    variable: "--font-geist-mono",
    subsets: ["latin"],
});

export const metadata: Metadata = {
    title: "Create Next App",
    description: "Generated by create next app",
};

interface TenantConfigResponse {
    id: string;
    name: string;
    themeConfig: {
        primaryColor: string;
        logoUrl: string;
    };
}

// 1. Helper to fetch config (cached)
async function getTenantConfig(tenantId: string): Promise<TenantConfigResponse | null> {
    try {
        const baseUrl = process.env.NEXT_PUBLIC_BACKEND_URL || "http://localhost:3000";
        const res = await fetch(`${baseUrl}/api/v1/tenants/${tenantId}`, {
            headers: {
                "X-Tenant-ID": tenantId,
            },
            next: {revalidate: 300}, // Cache for 5 minutes
        });

        if (!res.ok) return null;
        return await res.json();
    } catch (error) {
        console.error("Failed to fetch tenant theme config:", error);
        return null;
    }
}

// 2. Hex to HSL Converter for Shadcn/Tailwind
function hexToHslString(hex: string): string {
    hex = hex.replace(/^#/, '');
    let r = parseInt(hex.substring(0, 2), 16) / 255;
    let g = parseInt(hex.substring(2, 4), 16) / 255;
    let b = parseInt(hex.substring(4, 6), 16) / 255;

    let max = Math.max(r, g, b), min = Math.min(r, g, b);
    let h = 0, s = 0, l = (max + min) / 2;

    if (max !== min) {
        let d = max - min;
        s = l > 0.5 ? d / (2 - max - min) : d / (max + min);
        switch (max) {
            case r:
                h = (g - b) / d + (g < b ? 6 : 0);
                break;
            case g:
                h = (b - r) / d + 2;
                break;
            case b:
                h = (r - g) / d + 4;
                break;
        }
        h /= 6;
    }
    return `${Math.round(h * 360)} ${Math.round(s * 100)}% ${Math.round(l * 100)}%`;
}

export default async function TenantLayout({
                                               children,
                                               params
                                           }: {
    children: React.ReactNode,
    params: Promise<{ subdomain: string }>
}) {
    // 3. Await the params to get the raw subdomain if needed for UI/Links
    const {subdomain} = await params;

    // 4. Extract the securely resolved ID from our proxy.ts
    const reqHeaders = await headers();
    const tenantId = reqHeaders.get("x-tenant-id");

    if (!tenantId) {
        redirect("https://strive.lk/explore");
    }

    const tenantConfig = await getTenantConfig(tenantId);

    // Apply dynamic theming
    const rawHex = tenantConfig?.themeConfig?.primaryColor || "#ea580c";
    const dynamicPrimaryHsl = hexToHslString(rawHex);

    return (
        <html
            lang="en"
            className={cn("h-full", "antialiased", geistSans.variable, geistMono.variable, "font-sans", inter.variable)}
        >
        <body className="min-h-full flex flex-col">
        <div
            className="flex min-h-screen bg-zinc-950 text-white selection:bg-primary/30"
            style={{
                '--primary': dynamicPrimaryHsl,
            } as React.CSSProperties}
        >
            {/* Desktop Sidebar */}
            <aside className="hidden md:flex w-64 flex-col border-r border-white/5 bg-zinc-950 sticky top-0 h-screen">
                <Sidebar


                />
            </aside>

            {/* Main Content Area */}
            <div className="flex-1 flex flex-col min-w-0">
                <DashboardHeader/>
                <main className="flex-1 p-4 md:p-8 pb-24 md:pb-8 max-w-7xl mx-auto w-full">
                    {children}
                </main>
            </div>

            {/* Mobile Bottom Navigation */}
            <nav
                className="md:hidden fixed bottom-0 left-0 right-0 h-16 bg-zinc-900/80 backdrop-blur-lg border-t border-white/10 flex items-center justify-around px-6 z-50">
                <MobileNavItem icon={<LayoutDashboard size={20}/>} label="Home" active/>
                <MobileNavItem icon={<Search size={20}/>} label="Bookings"/>
                <MobileNavItem icon={<Wallet size={20}/>} label="Billing"/>
                <MobileNavItem icon={<Settings size={20}/>} label="Settings"/>
            </nav>
        </div>
        </body>
        </html>
    );
}

function MobileNavItem({icon, label, active = false}: { icon: React.ReactNode, label: string, active?: boolean }) {
    return (
        <div
            className={`flex flex-col items-center gap-1 transition-colors ${active ? 'text-primary' : 'text-zinc-500 hover:text-zinc-400'}`}>
            {icon}
            <span className="text-[10px] font-bold uppercase tracking-tighter">{label}</span>
        </div>
    );
}